In [10]:
from IPython.display import display, HTML
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
#InteractiveShell.ast_node_interactivity = "last"
from importlib import reload
import pandas as pd
%load_ext autoreload
%autoreload 2
pd.set_option("display.precision",2)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# BAU - Business As Usual
The BAU model is very simple: RT and RTSP are constantly at 22C.  Heating load is calculated from OAT by using the previously calculated heating model.

Inputs: 
  - Target year
  - A dataframe with a source of OAT
  
Output Dataframe: 
  - all house-state columns added
  - hload added
  - rload added = hload

In [17]:
import bau
reload(bau)
#dfIn = pd.read_pickle('wxhydro2018.pickle')[['OAT',']]
dfIn = pd.read_pickle('irradiance2014.pickle')[['OAT']]['2013']
#bo = bau.BAU(dfIn.loc[dfIn.index.year == 2013])
bo = bau.BAU(dfIn)
bo.apply()
df = bo.df
df.to_pickle('bau.pickle')

In [18]:
df

                     OAT  rt  rtsp  exheat  hload  rload  bcons
Dtime
2013-01-01 00:00:00  5.0  22    22       0   1.31   1.31   2.42
2013-01-01 01:00:00  4.5  22    22       0   1.36   1.36   2.46
2013-01-01 02:00:00  4.0  22    22       0   1.41   1.41   2.51
2013-01-01 03:00:00  3.3  22    22       0   1.47   1.47   2.57
2013-01-01 04:00:00  3.1  22    22       0   1.49   1.49   2.59
2013-01-01 05:00:00  3.1  22    22       0   1.49   1.49   2.59
2013-01-01 06:00:00  2.7  22    22       0   1.52   1.52   2.62
2013-01-01 07:00:00  2.6  22    22       0   1.53   1.53   2.63
2013-01-01 08:00:00  2.8  22    22       0   1.52   1.52   2.62
2013-01-01 09:00:00  2.8  22    22       0   1.52   1.52   2.62
2013-01-01 10:00:00  3.6  22    22       0   1.44   1.44   2.54
2013-01-01 11:00:00  3.5  22    22       0   1.45   1.45   2.55
2013-01-01 12:00:00  3.8  22    22       0   1.42   1.42   2.52
2013-01-01 13:00:00  3.8  22    22       0   1.42   1.42   2.52
2013-01-01 14:00:00  3.8  22    22       0   1.42   1.42   2.52
2013-01-01 15:00:00  3.6  22    22       0   1.44   1.44   2.54
2013-01-01 16:00:00  3.8  22    22       0   1.42   1.42   2.52
2013-01-01 17:00:00  3.5  22    22       0   1.45   1.45   2.55
2013-01-01 18:00:00  3.0  22    22       0   1.50   1.50   2.60
2013-01-01 19:00:00  2.8  22    22       0   1.52   1.52   2.62
2013-01-01 20:00:00  2.9  22    22       0   1.51   1.51   2.61
2013-01-01 21:00:00  3.5  22    22       0   1.45   1.45   2.55
2013-01-01 22:00:00  3.6  22    22       0   1.44   1.44   2.54
2013-01-01 23:00:00  3.1  22    22       0   1.49   1.49   2.59
2013-01-02 00:00:00  2.9  22    22       0   1.51   1.51   2.61
2013-01-02 01:00:00  3.6  22    22       0   1.44   1.44   2.54
2013-01-02 02:00:00  3.4  22    22       0   1.46   1.46   2.56
2013-01-02 03:00:00  3.7  22    22       0   1.43   1.43   2.53
2013-01-02 04:00:00  3.3  22    22       0   1.47   1.47   2.57
2013-01-02 05:00:00  3.6  22    22       0   1.44   1.44   2.54
...                  ...  ..   ...     ...    ...    ...    ...
2013-12-30 18:00:00  7.2  22    22       0   1.11   1.11   2.21
2013-12-30 19:00:00  7.3  22    22       0   1.11   1.11   2.21
2013-12-30 20:00:00  7.2  22    22       0   1.11   1.11   2.21
2013-12-30 21:00:00  6.8  22    22       0   1.15   1.15   2.25
2013-12-30 22:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-30 23:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 00:00:00  7.3  22    22       0   1.11   1.11   2.21
2013-12-31 01:00:00  7.2  22    22       0   1.11   1.11   2.21
2013-12-31 02:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 03:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 04:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 05:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 06:00:00  6.8  22    22       0   1.15   1.15   2.25
2013-12-31 07:00:00  6.7  22    22       0   1.16   1.16   2.26
2013-12-31 08:00:00  6.8  22    22       0   1.15   1.15   2.25
2013-12-31 09:00:00  6.9  22    22       0   1.14   1.14   2.24
2013-12-31 10:00:00  6.9  22    22       0   1.14   1.14   2.24
2013-12-31 11:00:00  6.9  22    22       0   1.14   1.14   2.24
2013-12-31 12:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 13:00:00  7.2  22    22       0   1.11   1.11   2.21
2013-12-31 14:00:00  7.4  22    22       0   1.10   1.10   2.20
2013-12-31 15:00:00  7.4  22    22       0   1.10   1.10   2.20
2013-12-31 16:00:00  7.4  22    22       0   1.10   1.10   2.20
2013-12-31 17:00:00  7.4  22    22       0   1.10   1.10   2.20
2013-12-31 18:00:00  7.3  22    22       0   1.11   1.11   2.21
2013-12-31 19:00:00  7.3  22    22       0   1.11   1.11   2.21
2013-12-31 20:00:00  7.2  22    22       0   1.11   1.11   2.21
2013-12-31 21:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 22:00:00  7.1  22    22       0   1.12   1.12   2.22
2013-12-31 23:00:00  6.8  22    22       0   1.15   1.15   2.25

[8760 rows x 7 columns]